horncad_config:
  type: HornCAD
  version: 2
  units: mm
  global:
    length: 315.6858016345398
    throat_radius: 12.7
    throat_angle_deg: 6
    conical_extension_length: 5.502349065841085
    effective_throat_radius: 13.278320190730035
    measured_total_length: 321.1881507003809
    mouth_width: 400
    mouth_height: 280
    mouth_sag: 60
    mouth_sag_h_enabled: true
    mouth_sag_v_enabled: true
  operating_intent:
    horizontal_coverage_deg: 50.0
    vertical_coverage_deg: 35.0
    crossover_hz: 500.0
    upper_frequency_hz: 5000.0
  body:
    mouth_rear_offset: 6
    mount_diameter: 140
    mount_flange_thickness: 12
    throat_start_wall_thickness: 6
    minimum_wall_thickness: 6
    screw_hole_count: 3
    screw_hole_diameter: 5
    screw_pattern_diameter: 110
    mount_fillet: 12
    stl_export_mode: body
  horizontal_basis:
    coverage_deg: 33.19865970319001
    k: 28.851292588172655
    n: 10
    solved_s: 1.2267234693558542
    mouth_exit_angle_deg: 86.84601395712046
    mouth_curvature_radius_mm: 581.5507454160303
    normalized_mouth_curvature_radius: 2.9077537270801512
  vertical_basis:
    coverage_deg: 42.45085781366632
    k: 43.619960213701205
    n: 10
    solved_s: 0.309043488248619
    mouth_exit_angle_deg: 78.646814974565
    mouth_curvature_radius_mm: 50.38243174709089
    normalized_mouth_curvature_radius: 0.35987451247922064
  section_modifier:
    mouth_squareness: 0.72
    squareness_morph_spline:
    - x: 0
      y: 0
      angle_deg: 0
      tension: 0.35
    - x: 1
      y: 1
      angle_deg: 0
      tension: 0.35
    horizontal_modifier:
      enabled: false
      profile_delta_spline:
      - x: 0
        y_mm: 0
        angle_deg: 6.003169
        tension: 0.35
      - x: 1
        y_mm: 0
        angle_deg: 74.168651
        tension: 0.35
      thickness_spline:
      - x: 0
        y: 1
        angle_deg: 0
        tension: 0.35
      - x: 1
        y: 0
        angle_deg: 0
        tension: 0.35
    vertical_modifier:
      enabled: false
      profile_delta_spline:
      - x: 0
        y_mm: 0
        angle_deg: 6.001823
        tension: 0.35
      - x: 1
        y_mm: 0
        angle_deg: 72.20737
        tension: 0.35
      thickness_spline:
      - x: 0
        y: 1
        angle_deg: 0
        tension: 0.35
      - x: 1
        y: 0
        angle_deg: 0
        tension: 0.35
  view:
    wire_density: 64
  export:
    stl_z_stations: 44
    stl_side_samples: 160
