horncad_config:
  type: HornCAD
  version: 2
  units: mm
  global:
    length: 312.82944049044664
    throat_radius: 12.7
    throat_angle_deg: 6
    conical_extension_length: 1.1163693637278453
    effective_throat_radius: 12.817335148248644
    measured_total_length: 313.9458098541745
    mouth_width: 400
    mouth_height: 280
    mouth_sag: 60
    mouth_sag_h_enabled: true
    mouth_sag_v_enabled: true
  operating_intent:
    horizontal_coverage_deg: 50.0
    vertical_coverage_deg: 35.0
    crossover_hz: 500.0
    upper_frequency_hz: 5000.0
  body:
    mouth_rear_offset: 6
    mount_diameter: 140
    mount_flange_thickness: 12
    throat_start_wall_thickness: 6
    minimum_wall_thickness: 6
    screw_hole_count: 3
    screw_hole_diameter: 5
    screw_pattern_diameter: 110
    mount_fillet: 12
    stl_export_mode: body
  horizontal_basis:
    coverage_deg: 51.188490142739454
    k: 55.85182632447123
    n: 10.443023614374816
    solved_s: 0.7116123369168105
    mouth_exit_angle_deg: 84.66306382306
    mouth_curvature_radius_mm: 210.12371899266807
    normalized_mouth_curvature_radius: 1.0506185949633404
  vertical_basis:
    coverage_deg: 31.614599409253742
    k: 55.88668602413757
    n: 4.469642182355355
    solved_s: 0.38190526971197547
    mouth_exit_angle_deg: 82.3926300235451
    mouth_curvature_radius_mm: 119.36950553343773
    normalized_mouth_curvature_radius: 0.8526393252388409
  section_modifier:
    mouth_squareness: 0.72
    squareness_morph_spline:
    - x: 0
      y: 0
      angle_deg: 0
      tension: 0.35
    - x: 1
      y: 1
      angle_deg: 0
      tension: 0.35
    horizontal_modifier:
      enabled: false
      profile_delta_spline:
      - x: 0
        y_mm: 0
        angle_deg: 6.003169
        tension: 0.35
      - x: 1
        y_mm: 0
        angle_deg: 74.168651
        tension: 0.35
      thickness_spline:
      - x: 0
        y: 1
        angle_deg: 0
        tension: 0.35
      - x: 1
        y: 0
        angle_deg: 0
        tension: 0.35
    vertical_modifier:
      enabled: false
      profile_delta_spline:
      - x: 0
        y_mm: 0
        angle_deg: 6.001823
        tension: 0.35
      - x: 1
        y_mm: 0
        angle_deg: 72.20737
        tension: 0.35
      thickness_spline:
      - x: 0
        y: 1
        angle_deg: 0
        tension: 0.35
      - x: 1
        y: 0
        angle_deg: 0
        tension: 0.35
  view:
    wire_density: 64
  export:
    stl_z_stations: 44
    stl_side_samples: 160
